/**
 * Builds sayarin-dark.json / sayarin-light.json from palette.oklch.json (OKLCH source → hex for VS Code).
 */
import { readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { formatHex8, parse } from "culori";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const palette = JSON.parse(readFileSync(join(root, "palette.oklch.json"), "utf8"));

function toHex(oklchString) {
  const c = parse(oklchString.trim());
  if (!c) throw new Error(`Invalid color: ${oklchString}`);
  return formatHex8(c);
}

function pick(variant, path) {
  const parts = path.split(".");
  let o = palette[variant];
  for (const p of parts) {
    o = o[p];
    if (o === undefined) throw new Error(`Missing palette ${variant}.${path}`);
  }
  return toHex(o);
}

/** @param {Record<string, string>} map */
function buildColors(variant, map) {
  const out = {};
  for (const [vscodeKey, path] of Object.entries(map)) {
    out[vscodeKey] = pick(variant, path);
  }
  return out;
}

const darkColorMap = {
  "activityBar.background": "ui.surfaceActivityBar",
  "activityBar.foreground": "ui.textPrimary",
  "activityBar.inactiveForeground": "ui.textInactive",
  "activityBarBadge.background": "ui.accentGold",
  "activityBarBadge.foreground": "ui.onAccent",
  "badge.background": "ui.accentGold",
  "badge.foreground": "ui.onAccent",
  "breadcrumb.background": "ui.surfaceEditor",
  "breadcrumb.foreground": "ui.textPrimary",
  "breadcrumb.focusForeground": "ui.textPrimary",
  "button.background": "ui.surfaceWidgetSelected",
  "button.foreground": "ui.textPrimary",
  "button.hoverBackground": "ui.surfaceButtonHover",
  "descriptionForeground": "ui.textMuted",
  "diffEditor.insertedTextBackground": "ui.diffAdd",
  "diffEditor.removedTextBackground": "ui.diffRemove",
  "dropdown.background": "ui.surfaceInput",
  "dropdown.foreground": "ui.textPrimary",
  "dropdown.border": "ui.borderDefault",
  "editor.background": "ui.surfaceEditor",
  "editor.foreground": "ui.textEditor",
  "editor.selectionBackground": "ui.selection",
  "editor.selectionHighlightBackground": "ui.selection2",
  "editor.inactiveSelectionBackground": "ui.selectionInactive",
  "editor.lineHighlightBackground": "ui.lineHighlight",
  "editor.rangeHighlightBackground": "ui.surfacePanel",
  "editorLineNumber.foreground": "ui.lineNumber",
  "editorLineNumber.activeForeground": "ui.accentGold",
  "editorCursor.foreground": "ui.accentGold",
  "editorWhitespace.foreground": "ui.whitespace",
  "editorIndentGuide.background": "ui.indentGuide",
  "editorIndentGuide.activeBackground": "ui.indentGuideActive",
  "editorGutter.background": "ui.surfaceEditor",
  "editorGutter.modifiedBackground": "ui.warning",
  "editorGutter.addedBackground": "syntax.string",
  "editorGutter.deletedBackground": "ui.error",
  "editorGroupHeader.tabsBackground": "ui.surfaceTabBar",
  "editorGroup.border": "ui.borderSubtle",
  "editorGroupHeader.border": "ui.borderSubtle",
  "editorGroup.dropBackground": "ui.dropTarget",
  "editorWidget.background": "ui.surfaceInput",
  "editorWidget.border": "ui.borderDefault",
  "editorSuggestWidget.background": "ui.surfaceInput",
  "editorSuggestWidget.border": "ui.borderDefault",
  "editorSuggestWidget.foreground": "ui.textPrimary",
  "editorSuggestWidget.highlightForeground": "ui.accentGold",
  "editorSuggestWidget.selectedBackground": "ui.surfaceWidgetSelected",
  "errorForeground": "ui.error",
  "focusBorder": "ui.accentGold",
  "foreground": "ui.textPrimary",
  "input.background": "ui.surfaceInput",
  "input.foreground": "ui.textPrimary",
  "input.border": "ui.borderDefault",
  "input.placeholderForeground": "ui.placeholder",
  "inputOption.activeBorder": "ui.accentGold",
  "list.activeSelectionBackground": "ui.surfaceWidgetSelected",
  "list.activeSelectionForeground": "ui.textPrimary",
  "list.hoverBackground": "ui.surfaceHover",
  "list.inactiveSelectionBackground": "ui.surfaceHover2",
  "list.focusBackground": "ui.surfaceWidgetSelected",
  "list.focusForeground": "ui.textPrimary",
  "list.highlightForeground": "ui.accentGoldBright",
  "list.deemphasizedForeground": "ui.textDim",
  "menu.background": "ui.surfaceInput",
  "menu.foreground": "ui.textPrimary",
  "menu.selectionBackground": "ui.surfaceWidgetSelected",
  "menu.border": "ui.borderDefault",
  "menubar.selectionBackground": "ui.surfaceHover",
  "merge.currentHeaderBackground": "ui.mergeCurrentBg",
  "merge.incomingHeaderBackground": "ui.mergeIncomingBg",
  "minimap.background": "ui.surfaceEditor",
  "notificationCenter.border": "ui.borderDefault",
  "notificationCenterHeader.background": "ui.surfaceInput",
  "notifications.background": "ui.surfaceInput",
  "notificationToast.border": "ui.borderDefault",
  "panel.background": "ui.surfaceTerminal",
  "panel.border": "ui.borderSubtle",
  "panelTitle.activeBorder": "ui.accentGold",
  "panelTitle.activeForeground": "ui.textPrimary",
  "panelTitle.inactiveForeground": "ui.textInactive",
  "peekView.border": "ui.accentGold",
  "peekViewEditor.background": "ui.surfaceEditor",
  "peekViewResult.background": "ui.surfacePanel",
  "pickerGroup.border": "ui.borderDefault",
  "pickerGroup.foreground": "ui.accentGold",
  "progressBar.background": "ui.accentGold",
  "quickInput.background": "ui.surfaceInput",
  "quickInput.foreground": "ui.textPrimary",
  "quickInputTitle.foreground": "ui.textPrimary",
  "scrollbar.shadow": "ui.transparent",
  "scrollbarSlider.background": "ui.scrollbar",
  "scrollbarSlider.hoverBackground": "ui.scrollbarHover",
  "scrollbarSlider.activeBackground": "ui.scrollbarActive",
  "sideBar.background": "ui.surfacePanel",
  "sideBar.foreground": "ui.textPrimary",
  "sideBarTitle.foreground": "ui.textPrimary",
  "sideBarSectionHeader.background": "ui.surfacePanel",
  "sideBarSectionHeader.foreground": "ui.textMuted",
  "statusBar.background": "ui.surfaceStatus",
  "statusBar.foreground": "ui.textPrimary",
  "statusBar.noFolderBackground": "ui.surfaceStatus",
  "statusBar.debuggingBackground": "ui.debugOrange",
  "statusBarItem.activeBackground": "ui.surfaceWidgetSelected",
  "statusBarItem.hoverBackground": "ui.surfaceHover",
  "statusBarItem.prominentForeground": "ui.accentGoldBright",
  "tab.activeBackground": "ui.surfaceEditor",
  "tab.inactiveBackground": "ui.surfaceTabBar",
  "tab.activeForeground": "ui.textPrimary",
  "tab.inactiveForeground": "ui.textInactive",
  "tab.activeBorderTop": "ui.accentGold",
  "tab.activeBorder": "ui.accentGold",
  "tab.border": "ui.borderSubtle",
  "toolbar.activeBackground": "ui.surfaceWidgetSelected",
  "titleBar.activeBackground": "ui.surfaceStatus",
  "titleBar.activeForeground": "ui.textPrimary",
  "titleBar.inactiveBackground": "ui.surfaceTabBar",
  "titleBar.inactiveForeground": "ui.textInactive",
  "tree.indentGuidesStroke": "ui.borderDefault",
  "walkThrough.embeddedEditorBackground": "ui.surfaceEditor",
  "welcomePage.background": "ui.surfaceEditor",
  "welcomePage.tileBackground": "ui.surfacePanel",
  "welcomePage.tileHoverBackground": "ui.welcomeTileHover",
  "welcomePage.tileBorder": "ui.borderDefault",
  "welcomePage.progress.background": "ui.welcomeProgressBg",
  "welcomePage.progress.foreground": "ui.accentGold",
  "widget.shadow": "ui.shadow",
  "widget.border": "ui.borderDefault",
  "editorHoverWidget.background": "ui.surfaceInput",
  "editorHoverWidget.border": "ui.borderDefault",
  "editorError.foreground": "ui.error",
  "editorWarning.foreground": "ui.warning",
  "editorInfo.foreground": "ui.info",
  "editorHint.foreground": "ui.accentGold",
  "textLink.foreground": "ui.accentGoldBright",
  "textLink.activeForeground": "ui.accentGoldHot",
  "gitDecoration.addedResourceForeground": "syntax.string",
  "gitDecoration.modifiedResourceForeground": "ui.warning",
  "gitDecoration.deletedResourceForeground": "ui.error",
  "gitDecoration.untrackedResourceForeground": "syntax.string",
  "gitDecoration.ignoredResourceForeground": "ui.gitIgnored",
  "gitDecoration.conflictingResourceForeground": "ui.warning",
  "debugToolBar.background": "ui.surfaceInput",
  "debugExceptionWidget.background": "ui.debugBg",
  "debugExceptionWidget.border": "ui.debugBorder",
  "terminal.background": "ui.surfaceTerminal",
  "terminal.foreground": "terminal.foreground",
  "terminal.ansiBlack": "terminal.black",
  "terminal.ansiRed": "terminal.red",
  "terminal.ansiGreen": "terminal.green",
  "terminal.ansiYellow": "terminal.yellow",
  "terminal.ansiBlue": "terminal.blue",
  "terminal.ansiMagenta": "terminal.magenta",
  "terminal.ansiCyan": "terminal.cyan",
  "terminal.ansiWhite": "terminal.white",
  "terminal.ansiBrightBlack": "terminal.brightBlack",
  "terminal.ansiBrightRed": "terminal.brightRed",
  "terminal.ansiBrightGreen": "terminal.brightGreen",
  "terminal.ansiBrightYellow": "terminal.brightYellow",
  "terminal.ansiBrightBlue": "terminal.brightBlue",
  "terminal.ansiBrightMagenta": "terminal.brightMagenta",
  "terminal.ansiBrightCyan": "terminal.brightCyan",
  "terminal.ansiBrightWhite": "terminal.brightWhite",
};

const lightColorMap = {
  "activityBar.background": "ui.surfaceActivityBar",
  "activityBar.foreground": "ui.textPrimary",
  "activityBar.inactiveForeground": "ui.textInactive",
  "activityBarBadge.background": "ui.accentGold",
  "activityBarBadge.foreground": "ui.onAccent",
  "badge.background": "ui.accentGold",
  "badge.foreground": "ui.onAccent",
  "breadcrumb.background": "ui.surfaceEditor",
  "breadcrumb.foreground": "ui.textEditor",
  "breadcrumb.focusForeground": "ui.textPrimary",
  "button.background": "ui.surfaceWidgetSelected",
  "button.foreground": "ui.textPrimary",
  "button.hoverBackground": "ui.surfaceButtonHover",
  "descriptionForeground": "ui.textMuted",
  "diffEditor.insertedTextBackground": "ui.diffAdd",
  "diffEditor.removedTextBackground": "ui.diffRemove",
  "dropdown.background": "ui.surfaceInput",
  "dropdown.foreground": "ui.textPrimary",
  "dropdown.border": "ui.borderDefault",
  "editor.background": "ui.surfaceEditor",
  "editor.foreground": "ui.textEditor",
  "editor.selectionBackground": "ui.selection",
  "editor.selectionHighlightBackground": "ui.selection2",
  "editor.inactiveSelectionBackground": "ui.selectionInactive",
  "editor.lineHighlightBackground": "ui.lineHighlight",
  "editor.rangeHighlightBackground": "ui.surfacePanel",
  "editorLineNumber.foreground": "ui.lineNumber",
  "editorLineNumber.activeForeground": "ui.accentGold",
  "editorCursor.foreground": "ui.accentGold",
  "editorWhitespace.foreground": "ui.whitespace",
  "editorIndentGuide.background": "ui.indentGuide",
  "editorIndentGuide.activeBackground": "ui.indentGuideActive",
  "editorGutter.background": "ui.surfaceEditor",
  "editorGutter.modifiedBackground": "ui.warning",
  "editorGutter.addedBackground": "syntax.string",
  "editorGutter.deletedBackground": "ui.error",
  "editorGroupHeader.tabsBackground": "ui.surfaceTabBar",
  "editorGroup.border": "ui.borderSubtle",
  "editorGroupHeader.border": "ui.borderSubtle",
  "editorGroup.dropBackground": "ui.dropTarget",
  "editorWidget.background": "ui.surfaceInput",
  "editorWidget.border": "ui.borderDefault",
  "editorSuggestWidget.background": "ui.surfaceInput",
  "editorSuggestWidget.border": "ui.borderDefault",
  "editorSuggestWidget.foreground": "ui.textPrimary",
  "editorSuggestWidget.highlightForeground": "ui.accentGold",
  "editorSuggestWidget.selectedBackground": "ui.surfaceWidgetSelected",
  "errorForeground": "ui.error",
  "focusBorder": "ui.accentGold",
  "foreground": "ui.textPrimary",
  "input.background": "ui.surfaceInput",
  "input.foreground": "ui.textPrimary",
  "input.border": "ui.borderDefault",
  "input.placeholderForeground": "ui.placeholder",
  "inputOption.activeBorder": "ui.accentGold",
  "list.activeSelectionBackground": "ui.surfaceWidgetSelected",
  "list.activeSelectionForeground": "ui.textPrimary",
  "list.hoverBackground": "ui.surfaceHover",
  "list.inactiveSelectionBackground": "ui.surfaceHover2",
  "list.focusBackground": "ui.surfaceWidgetSelected",
  "list.focusForeground": "ui.textPrimary",
  "list.highlightForeground": "ui.accentGoldBright",
  "list.deemphasizedForeground": "ui.textDim",
  "menu.background": "ui.surfaceInput",
  "menu.foreground": "ui.textPrimary",
  "menu.selectionBackground": "ui.surfaceWidgetSelected",
  "menu.border": "ui.borderDefault",
  "menubar.selectionBackground": "ui.surfaceHover",
  "merge.currentHeaderBackground": "ui.mergeCurrentBg",
  "merge.incomingHeaderBackground": "ui.mergeIncomingBg",
  "minimap.background": "ui.surfaceEditor",
  "notificationCenter.border": "ui.borderDefault",
  "notificationCenterHeader.background": "ui.surfaceInput",
  "notifications.background": "ui.surfaceInput",
  "notificationToast.border": "ui.borderDefault",
  "panel.background": "ui.surfaceTerminal",
  "panel.border": "ui.borderSubtle",
  "panelTitle.activeBorder": "ui.accentGold",
  "panelTitle.activeForeground": "ui.textPrimary",
  "panelTitle.inactiveForeground": "ui.textInactive",
  "peekView.border": "ui.accentGold",
  "peekViewEditor.background": "ui.surfaceEditor",
  "peekViewResult.background": "ui.surfacePanel",
  "pickerGroup.border": "ui.borderDefault",
  "pickerGroup.foreground": "ui.accentGold",
  "progressBar.background": "ui.accentGold",
  "quickInput.background": "ui.surfaceInput",
  "quickInput.foreground": "ui.textPrimary",
  "quickInputTitle.foreground": "ui.textPrimary",
  "scrollbar.shadow": "ui.transparent",
  "scrollbarSlider.background": "ui.scrollbar",
  "scrollbarSlider.hoverBackground": "ui.scrollbarHover",
  "scrollbarSlider.activeBackground": "ui.scrollbarActive",
  "sideBar.background": "ui.surfacePanel",
  "sideBar.foreground": "ui.textPrimary",
  "sideBarTitle.foreground": "ui.textEditor",
  "sideBarSectionHeader.background": "ui.surfacePanel",
  "sideBarSectionHeader.foreground": "ui.textMuted",
  "statusBar.background": "ui.surfaceStatus",
  "statusBar.foreground": "ui.textPrimary",
  "statusBar.noFolderBackground": "ui.surfaceStatus",
  "statusBar.debuggingBackground": "ui.debugOrange",
  "statusBarItem.activeBackground": "ui.surfaceWidgetSelected",
  "statusBarItem.hoverBackground": "ui.surfaceHover",
  "statusBarItem.prominentForeground": "ui.accentGoldBright",
  "tab.activeBackground": "ui.surfaceEditor",
  "tab.inactiveBackground": "ui.surfaceTabBar",
  "tab.activeForeground": "ui.textPrimary",
  "tab.inactiveForeground": "ui.textInactive",
  "tab.activeBorderTop": "ui.accentGold",
  "tab.activeBorder": "ui.accentGold",
  "tab.border": "ui.borderSubtle",
  "toolbar.activeBackground": "ui.surfaceWidgetSelected",
  "titleBar.activeBackground": "ui.surfaceStatus",
  "titleBar.activeForeground": "ui.textPrimary",
  "titleBar.inactiveBackground": "ui.surfaceTabBar",
  "titleBar.inactiveForeground": "ui.textInactive",
  "tree.indentGuidesStroke": "ui.borderDefault",
  "walkThrough.embeddedEditorBackground": "ui.surfaceEditor",
  "welcomePage.background": "ui.surfaceEditor",
  "welcomePage.tileBackground": "ui.surfacePanel",
  "welcomePage.tileHoverBackground": "ui.welcomeTileHover",
  "welcomePage.tileBorder": "ui.borderDefault",
  "welcomePage.progress.background": "ui.welcomeProgressBg",
  "welcomePage.progress.foreground": "ui.accentGold",
  "widget.shadow": "ui.shadow",
  "widget.border": "ui.borderDefault",
  "editorHoverWidget.background": "ui.surfaceInput",
  "editorHoverWidget.border": "ui.borderDefault",
  "editorError.foreground": "ui.error",
  "editorWarning.foreground": "ui.warning",
  "editorInfo.foreground": "ui.info",
  "editorHint.foreground": "ui.accentGold",
  "textLink.foreground": "ui.accentGoldBright",
  "textLink.activeForeground": "ui.accentGoldHot",
  "gitDecoration.addedResourceForeground": "syntax.string",
  "gitDecoration.modifiedResourceForeground": "ui.warning",
  "gitDecoration.deletedResourceForeground": "ui.error",
  "gitDecoration.untrackedResourceForeground": "syntax.string",
  "gitDecoration.ignoredResourceForeground": "ui.gitIgnored",
  "gitDecoration.conflictingResourceForeground": "ui.warning",
  "debugToolBar.background": "ui.surfaceInput",
  "debugExceptionWidget.background": "ui.debugBg",
  "debugExceptionWidget.border": "ui.debugBorder",
  "terminal.background": "ui.surfaceTerminal",
  "terminal.foreground": "terminal.foreground",
  "terminal.ansiBlack": "terminal.black",
  "terminal.ansiRed": "terminal.red",
  "terminal.ansiGreen": "terminal.green",
  "terminal.ansiYellow": "terminal.yellow",
  "terminal.ansiBlue": "terminal.blue",
  "terminal.ansiMagenta": "terminal.magenta",
  "terminal.ansiCyan": "terminal.cyan",
  "terminal.ansiWhite": "terminal.white",
  "terminal.ansiBrightBlack": "terminal.brightBlack",
  "terminal.ansiBrightRed": "terminal.brightRed",
  "terminal.ansiBrightGreen": "terminal.brightGreen",
  "terminal.ansiBrightYellow": "terminal.brightYellow",
  "terminal.ansiBrightBlue": "terminal.brightBlue",
  "terminal.ansiBrightMagenta": "terminal.brightMagenta",
  "terminal.ansiBrightCyan": "terminal.brightCyan",
  "terminal.ansiBrightWhite": "terminal.brightWhite",
};

const tokenRules = [
  ["comment", "comment", "italic"],
  ["comment.block.documentation,comment.block.doc", "commentDoc", "italic"],
  ["string,string.quoted", "string", null],
  ["constant.character.escape", "stringEscape", null],
  ["string.regexp,string.quoted.regexp", "stringRegex", null],
  ["string.special,string.other", "stringSpecial", null],
  ["constant.other.symbol", "symbol", null],
  ["keyword,storage.type,storage.modifier", "keyword", null],
  ["keyword.operator", "operator", null],
  ["constant.numeric,constant.language", "number", null],
  ["constant,constant.other", "constant", null],
  ["entity.name.function,support.function,meta.function-call", "function", null],
  ["support.function.builtin", "functionBuiltin", null],
  ["entity.name.type,entity.name.class,support.type,entity.other.inherited-class", "type", null],
  ["entity.name.enum", "enum", null],
  ["variable,variable.other,variable.other.readwrite", "variable", null],
  ["variable.other.member,variable.other.property", "property", null],
  ["support.type.property-name,meta.property-name", "property", null],
  ["variable.language,variable.parameter", "variableSpecial", null],
  ["entity.name.namespace", "namespace", null],
  ["entity.other.attribute-name", "attribute", null],
  ["entity.name.tag", "tag", null],
  ["entity.name.function.constructor", "constructor", null],
  ["meta.embedded,string.interpolated,meta.template.expression", "embedded", null],
  ["punctuation.definition,punctuation.section,meta.brace,meta.block", "punctBracket", null],
  [
    "punctuation.separator,punctuation.terminator,punctuation.accessor,punctuation.definition.parameters",
    "punctSep",
    null,
  ],
  ["punctuation.definition.list,markup.list", "punctList", null],
  ["punctuation.definition.markup", "punctMarkup", null],
  ["punctuation.definition.template-expression", "punctTemplate", null],
  [
    "entity.other.attribute-name.pseudo-class,entity.other.attribute-name.pseudo-element",
    "pseudo",
    null,
  ],
  ["entity.name.tag.css,entity.name.tag.scss", "cssTag", null],
  ["meta.preprocessor", "preproc", null],
  ["markup.heading,entity.name.section", "heading", "bold"],
  ["markup.underline.link,string.other.link", "link", "italic"],
  ["markup.underline", "linkUnderline", null],
  ["entity.name.label", "label", null],
  ["markup.italic", "label", "italic"],
  ["markup.bold", "label", "bold"],
  ["meta.hint,comment.line.annotation", "hint", null],
  ["meta.embedded.line,source.embedded", "embeddedLine", "italic"],
  ["support.constant,variable.other.constant", "supportConstant", null],
  ["entity.name.variant", "variant", null],
  ["text.literal,markup.raw", "textLiteral", null],
];

function buildTokenColors(variant) {
  return tokenRules.map(([scopeStr, syntaxKey, fontStyle]) => {
    const scope = scopeStr.split(",").map((s) => s.trim());
    const fg = pick(variant, `syntax.${syntaxKey}`);
    const settings = { foreground: fg };
    if (fontStyle === "italic") settings.fontStyle = "italic";
    if (fontStyle === "bold") settings.fontStyle = "bold";
    return { scope, settings };
  });
}

const darkColors = buildColors("dark", darkColorMap);

const lightColors = buildColors("light", lightColorMap);

const darkTheme = {
  name: "Sayarin Dark",
  type: "dark",
  colors: darkColors,
  tokenColors: buildTokenColors("dark"),
};

const lightTheme = {
  name: "Sayarin Light",
  type: "light",
  colors: lightColors,
  tokenColors: buildTokenColors("light"),
};

writeFileSync(join(root, "themes", "sayarin-dark.json"), JSON.stringify(darkTheme, null, 2) + "\n");
writeFileSync(join(root, "themes", "sayarin-light.json"), JSON.stringify(lightTheme, null, 2) + "\n");

console.log("Wrote themes/sayarin-dark.json and themes/sayarin-light.json");
